In [1]:
import pandas as pd

match_20=pd.read_csv('D:/Final_Project/data/match_20_data.csv',index_col=0)
match_21=pd.read_csv('D:/Final_Project/data/match_21_data.csv',index_col=0)
champ_20=pd.read_csv('D:/Final_Project/data/champion_20.csv',index_col=0)
champ_21=pd.read_csv('D:/Final_Project/data/champion_21.csv',index_col=0)
spell=pd.read_csv('D:/Final_Project/data/spellid.csv',index_col=0)

In [2]:
match_20

,play_time,result,blue_1_champ,blue_1_spell1,blue_1_spell2,blue_1_kill,blue_1_death,blue_1_assist,blue_1_totaldamage_dealt,blue_1_totaldamage_taken,...,red_5_champ,red_5_spell1,red_5_spell2,red_5_kill,red_5_death,red_5_assist,red_5_totaldamage_dealt,red_5_totaldamage_taken,red_5_visionscore,red_5_cs
0,1323,0,7,1,4,3,6,3,71369,17255,...,421,11,4,7,2,13,146312,25898,36,21
1,1317,1,236,14,4,3,5,2,91081,15543,...,15,4,7,0,2,0,83071,9241,10,182
2,932,0,235,4,3,0,4,1,19098,6494,...,82,4,12,1,1,3,67175,6721,12,129
3,2098,0,111,4,14,4,9,11,35821,27058,...,157,4,1,6,7,13,180574,25018,37,217
4,2344,1,145,4,7,7,12,12,269340,33275,...,350,3,7,3,3,34,45127,5891,91,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26843,1468,0,79,4,11,3,6,11,111109,23414,...,2,4,11,6,5,6,151357,28571,35,39
26844,970,0,350,14,3,2,6,17,19435,8042,...,72,4,11,5,0,9,102880,10950,11,39
26845,1480,0,134,7,4,1,3,3,73126,11044,...,141,11,4,2,5,7,129053,21894,31,10
26846,1837,1,59,4,11,3,6,17,122445,31571,...,68,12,4,3,6,7,149570,25492,18,186
26847,948,1,58,12,4,2,0,6,65938,8956,...,412,4,14,0,2,1,10681,4165,20,22

In [3]:
match_21

,play_time,result,blue_1_champ,blue_1_spell1,blue_1_spell2,blue_1_kill,blue_1_death,blue_1_assist,blue_1_totaldamage_dealt,blue_1_totaldamage_taken,...,red_5_champ,red_5_spell1,red_5_spell2,red_5_kill,red_5_death,red_5_assist,red_5_totaldamage_dealt,red_5_totaldamage_taken,red_5_visionscore,red_5_cs
0,2241,0,7,12,4,4,5,18,156358,37416,...,64,11,4,9,8,11,143137,51158,47,31
1,1022,0,13,4,12,0,1,0,73834,6213,...,111,14,4,2,0,9,20522,4193,32,35
2,2056,1,36,12,4,1,5,11,148044,32263,...,7,12,4,10,7,9,139167,31081,28,164
3,1378,1,777,12,4,11,4,4,152755,17974,...,48,11,4,2,8,4,80229,30363,31,16
4,1265,1,523,1,4,5,1,15,108625,12931,...,142,14,4,2,3,4,73738,8879,21,135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13368,1363,1,412,14,4,2,4,12,16639,8032,...,134,4,12,2,2,5,85185,11636,8,166
13369,1553,1,39,4,12,10,4,2,213285,23667,...,58,4,12,2,3,2,108021,29559,24,193
13370,1143,1,115,4,12,5,2,8,102764,6862,...,240,14,4,0,7,2,22963,20706,11,50
13371,1261,0,360,1,4,4,6,3,80037,12581,...,115,12,4,17,2,7,154117,8985,27,168
13372,1883,0,203,7,4,8,6,7,161232,35964,...,43,3,4,3,3,12,27776,16274,110,12

In [4]:
champ_20

,version,name,champId,hp,hpperlevel,mp,mpperlevel,movespeed,armor,armorperlevel,...,hpregen,hpregenperlevel,mpregen,mpregenperlevel,crit,critperlevel,attackdamage,attackdamageperlevel,attackspeedperlevel,attackspeed
0,10.6.1,Aatrox,266,580.00,90,0.0,0.0,345,38.000,3.25,...,3.0,1.00,0.000,0.000,0,0,60.000,5.00,2.500,0.651
1,10.6.1,Ahri,103,526.00,92,418.0,25.0,330,20.880,3.50,...,6.5,0.60,8.000,0.800,0,0,53.040,3.00,2.000,0.668
2,10.6.1,Akali,84,575.00,95,200.0,0.0,345,23.000,3.50,...,8.0,0.50,50.000,0.000,0,0,62.400,3.30,3.200,0.625
3,10.6.1,Alistar,12,600.00,106,350.0,40.0,330,44.000,3.50,...,8.5,0.85,8.500,0.800,0,0,62.000,3.75,2.125,0.625
4,10.6.1,Amumu,32,613.12,84,287.2,40.0,335,33.000,3.80,...,9.0,0.85,7.382,0.525,0,0,53.380,3.80,2.180,0.736
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,10.6.1,Zed,238,584.00,85,200.0,0.0,345,32.000,3.50,...,7.0,0.65,50.000,0.000,0,0,63.000,3.40,3.300,0.651
144,10.6.1,Ziggs,115,536.00,92,480.0,23.5,325,21.544,3.30,...,6.5,0.60,8.000,0.800,0,0,54.208,3.10,2.000,0.656
145,10.6.1,Zilean,26,504.00,82,452.0,30.0,335,24.000,3.80,...,5.5,0.50,11.335,0.800,0,0,51.640,3.00,2.130,0.625
146,10.6.1,Zoe,142,560.00,92,425.0,25.0,340,20.800,3.50,...,6.5,0.60,8.000,0.650,0,0,58.000,3.30,2.500,0.625
147,10.6.1,Zyra,143,504.00,79,418.0,25.0,340,29.000,3.00,...,5.5,0.50,13.000,0.400,0,0,53.376,3.20,2.110,0.625

In [5]:
champ_21

,version,name,champId,hp,hpperlevel,mp,mpperlevel,movespeed,armor,armorperlevel,...,hpregen,hpregenperlevel,mpregen,mpregenperlevel,crit,critperlevel,attackdamage,attackdamageperlevel,attackspeedperlevel,attackspeed
0,11.15.1,Aatrox,266,580.0,90,0.0,0.0,345,38,3.25,...,3.00,1.00,0.000,0.00,0,0,60.0,5.00,2.500,0.651
1,11.15.1,Ahri,103,526.0,92,418.0,25.0,330,21,3.50,...,5.50,0.60,8.000,0.80,0,0,53.0,3.00,2.000,0.668
2,11.15.1,Akali,84,500.0,105,200.0,0.0,345,23,3.50,...,8.00,0.50,50.000,0.00,0,0,62.0,3.30,3.200,0.625
3,11.15.1,Akshan,166,530.0,90,350.0,40.0,330,26,3.00,...,3.75,0.65,8.175,0.70,0,0,50.0,3.50,2.500,0.638
4,11.15.1,Alistar,12,600.0,106,350.0,40.0,330,44,3.50,...,8.50,0.85,8.500,0.80,0,0,62.0,3.75,2.125,0.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,11.15.1,Zed,238,584.0,85,200.0,0.0,345,32,3.50,...,7.00,0.65,50.000,0.00,0,0,63.0,3.40,3.300,0.651
152,11.15.1,Ziggs,115,536.0,92,420.0,23.5,325,22,3.30,...,6.50,0.60,8.000,0.80,0,0,54.0,3.10,2.000,0.656
153,11.15.1,Zilean,26,504.0,82,452.0,50.0,335,24,3.80,...,5.50,0.50,11.340,0.80,0,0,52.0,3.00,2.130,0.625
154,11.15.1,Zoe,142,560.0,92,425.0,25.0,340,21,3.50,...,6.50,0.60,8.000,0.65,0,0,58.0,3.30,2.500,0.625
155,11.15.1,Zyra,143,504.0,79,418.0,25.0,340,29,3.00,...,5.50,0.50,13.000,0.40,0,0,53.0,3.20,2.110,0.625

In [6]:
spell

       name  spellId
0   Barrier       21
1   Cleanse        1
2    Ignite       14
3   Exhaust        3
4     Flash        4
5     Ghost        6
6      Heal        7
7   Clarity       13
8     Smite       11
9  Teleport       12

In [7]:
def champId20_to_name(id):
    champ_20_tmp=champ_20.set_index('champId')
    tmp=dict(champ_20_tmp['name'])
    switcher=tmp
    return switcher.get(id)

def champId21_to_name(id):
    champ_21_tmp=champ_21.set_index('champId')
    tmp=dict(champ_21_tmp['name'])
    switcher=tmp
    return switcher.get(id)
def spellId_to_name(id):
    spell_tmp=spell.set_index('spellId')
    tmp=dict(spell_tmp['name'])
    switcher=tmp
    return switcher.get(id)

In [8]:
from tqdm import tqdm_notebook

In [9]:
for x in (2,12,22,32,42,52,62,72,82,92):
    for i in tqdm_notebook(range(len(match_20))):
        match_20.iloc[i,x]=champId20_to_name(match_20.iloc[i,x])
match_20

<ipython-input-9-b7903b1b3771>:2: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(len(match_20))):

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

,play_time,result,blue_1_champ,blue_1_spell1,blue_1_spell2,blue_1_kill,blue_1_death,blue_1_assist,blue_1_totaldamage_dealt,blue_1_totaldamage_taken,...,red_5_champ,red_5_spell1,red_5_spell2,red_5_kill,red_5_death,red_5_assist,red_5_totaldamage_dealt,red_5_totaldamage_taken,red_5_visionscore,red_5_cs
0,1323,0,Leblanc,1,4,3,6,3,71369,17255,...,RekSai,11,4,7,2,13,146312,25898,36,21
1,1317,1,Lucian,14,4,3,5,2,91081,15543,...,Sivir,4,7,0,2,0,83071,9241,10,182
2,932,0,Senna,4,3,0,4,1,19098,6494,...,Mordekaiser,4,12,1,1,3,67175,6721,12,129
3,2098,0,Nautilus,4,14,4,9,11,35821,27058,...,Yasuo,4,1,6,7,13,180574,25018,37,217
4,2344,1,Kaisa,4,7,7,12,12,269340,33275,...,Yuumi,3,7,3,3,34,45127,5891,91,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26843,1468,0,Gragas,4,11,3,6,11,111109,23414,...,Olaf,4,11,6,5,6,151357,28571,35,39
26844,970,0,Yuumi,14,3,2,6,17,19435,8042,...,Skarner,4,11,5,0,9,102880,10950,11,39
26845,1480,0,Syndra,7,4,1,3,3,73126,11044,...,Kayn,11,4,2,5,7,129053,21894,31,10
26846,1837,1,JarvanIV,4,11,3,6,17,122445,31571,...,Rumble,12,4,3,6,7,149570,25492,18,186
26847,948,1,Renekton,12,4,2,0,6,65938,8956,...,Thresh,4,14,0,2,1,10681,4165,20,22

In [10]:
for x in (2,12,22,32,42,52,62,72,82,92):
    for i in tqdm_notebook(range(len(match_21))):
        match_21.iloc[i,x]=champId21_to_name(match_21.iloc[i,x])
match_21

<ipython-input-10-1e5ebaae5f50>:2: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(len(match_21))):

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

,play_time,result,blue_1_champ,blue_1_spell1,blue_1_spell2,blue_1_kill,blue_1_death,blue_1_assist,blue_1_totaldamage_dealt,blue_1_totaldamage_taken,...,red_5_champ,red_5_spell1,red_5_spell2,red_5_kill,red_5_death,red_5_assist,red_5_totaldamage_dealt,red_5_totaldamage_taken,red_5_visionscore,red_5_cs
0,2241,0,Leblanc,12,4,4,5,18,156358,37416,...,LeeSin,11,4,9,8,11,143137,51158,47,31
1,1022,0,Ryze,4,12,0,1,0,73834,6213,...,Nautilus,14,4,2,0,9,20522,4193,32,35
2,2056,1,DrMundo,12,4,1,5,11,148044,32263,...,Leblanc,12,4,10,7,9,139167,31081,28,164
3,1378,1,Yone,12,4,11,4,4,152755,17974,...,Trundle,11,4,2,8,4,80229,30363,31,16
4,1265,1,Aphelios,1,4,5,1,15,108625,12931,...,Zoe,14,4,2,3,4,73738,8879,21,135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13368,1363,1,Thresh,14,4,2,4,12,16639,8032,...,Syndra,4,12,2,2,5,85185,11636,8,166
13369,1553,1,Irelia,4,12,10,4,2,213285,23667,...,Renekton,4,12,2,3,2,108021,29559,24,193
13370,1143,1,Ziggs,4,12,5,2,8,102764,6862,...,Kled,14,4,0,7,2,22963,20706,11,50
13371,1261,0,Samira,1,4,4,6,3,80037,12581,...,Ziggs,12,4,17,2,7,154117,8985,27,168
13372,1883,0,Kindred,7,4,8,6,7,161232,35964,...,Karma,3,4,3,3,12,27776,16274,110,12

In [11]:
for x in (3,4,13,14,23,24,33,34,43,44,53,54,63,64,73,74,83,84,93,94):
    for i in tqdm_notebook(range(len(match_20))):
        match_20.iloc[i,x]=spellId_to_name(match_20.iloc[i,x])
match_20

<ipython-input-11-75c598c714b1>:2: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(len(match_20))):

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=26848.0), HTML(value='')))

,play_time,result,blue_1_champ,blue_1_spell1,blue_1_spell2,blue_1_kill,blue_1_death,blue_1_assist,blue_1_totaldamage_dealt,blue_1_totaldamage_taken,...,red_5_champ,red_5_spell1,red_5_spell2,red_5_kill,red_5_death,red_5_assist,red_5_totaldamage_dealt,red_5_totaldamage_taken,red_5_visionscore,red_5_cs
0,1323,0,Leblanc,Cleanse,Flash,3,6,3,71369,17255,...,RekSai,Smite,Flash,7,2,13,146312,25898,36,21
1,1317,1,Lucian,Ignite,Flash,3,5,2,91081,15543,...,Sivir,Flash,Heal,0,2,0,83071,9241,10,182
2,932,0,Senna,Flash,Exhaust,0,4,1,19098,6494,...,Mordekaiser,Flash,Teleport,1,1,3,67175,6721,12,129
3,2098,0,Nautilus,Flash,Ignite,4,9,11,35821,27058,...,Yasuo,Flash,Cleanse,6,7,13,180574,25018,37,217
4,2344,1,Kaisa,Flash,Heal,7,12,12,269340,33275,...,Yuumi,Exhaust,Heal,3,3,34,45127,5891,91,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26843,1468,0,Gragas,Flash,Smite,3,6,11,111109,23414,...,Olaf,Flash,Smite,6,5,6,151357,28571,35,39
26844,970,0,Yuumi,Ignite,Exhaust,2,6,17,19435,8042,...,Skarner,Flash,Smite,5,0,9,102880,10950,11,39
26845,1480,0,Syndra,Heal,Flash,1,3,3,73126,11044,...,Kayn,Smite,Flash,2,5,7,129053,21894,31,10
26846,1837,1,JarvanIV,Flash,Smite,3,6,17,122445,31571,...,Rumble,Teleport,Flash,3,6,7,149570,25492,18,186
26847,948,1,Renekton,Teleport,Flash,2,0,6,65938,8956,...,Thresh,Flash,Ignite,0,2,1,10681,4165,20,22

In [12]:
for x in (3,4,13,14,23,24,33,34,43,44,53,54,63,64,73,74,83,84,93,94):
    for i in tqdm_notebook(range(len(match_21))):
        match_21.iloc[i,x]=spellId_to_name(match_21.iloc[i,x])
match_21

<ipython-input-12-8a39a251336d>:2: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(len(match_21))):

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=13373.0), HTML(value='')))

,play_time,result,blue_1_champ,blue_1_spell1,blue_1_spell2,blue_1_kill,blue_1_death,blue_1_assist,blue_1_totaldamage_dealt,blue_1_totaldamage_taken,...,red_5_champ,red_5_spell1,red_5_spell2,red_5_kill,red_5_death,red_5_assist,red_5_totaldamage_dealt,red_5_totaldamage_taken,red_5_visionscore,red_5_cs
0,2241,0,Leblanc,Teleport,Flash,4,5,18,156358,37416,...,LeeSin,Smite,Flash,9,8,11,143137,51158,47,31
1,1022,0,Ryze,Flash,Teleport,0,1,0,73834,6213,...,Nautilus,Ignite,Flash,2,0,9,20522,4193,32,35
2,2056,1,DrMundo,Teleport,Flash,1,5,11,148044,32263,...,Leblanc,Teleport,Flash,10,7,9,139167,31081,28,164
3,1378,1,Yone,Teleport,Flash,11,4,4,152755,17974,...,Trundle,Smite,Flash,2,8,4,80229,30363,31,16
4,1265,1,Aphelios,Cleanse,Flash,5,1,15,108625,12931,...,Zoe,Ignite,Flash,2,3,4,73738,8879,21,135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13368,1363,1,Thresh,Ignite,Flash,2,4,12,16639,8032,...,Syndra,Flash,Teleport,2,2,5,85185,11636,8,166
13369,1553,1,Irelia,Flash,Teleport,10,4,2,213285,23667,...,Renekton,Flash,Teleport,2,3,2,108021,29559,24,193
13370,1143,1,Ziggs,Flash,Teleport,5,2,8,102764,6862,...,Kled,Ignite,Flash,0,7,2,22963,20706,11,50
13371,1261,0,Samira,Cleanse,Flash,4,6,3,80037,12581,...,Ziggs,Teleport,Flash,17,2,7,154117,8985,27,168
13372,1883,0,Kindred,Heal,Flash,8,6,7,161232,35964,...,Karma,Exhaust,Flash,3,3,12,27776,16274,110,12

In [13]:
match_20.to_csv('D:/Final_Project/data/match_20_final_data.csv',encoding='utf-8-sig')
match_21.to_csv('D:/Final_Project/data/match_21_final_data.csv',encoding='utf-8-sig')